version: "3.3"
services:
  spark-master:
    image: apache-spark-instance
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/apps
       - ./data:/opt/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    container_name: spark-master
  spark-worker-1:
    image: apache-spark-instance
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
       - ./apps:/opt/apps
       - ./data:/opt/data
    container_name: spark-worker-1
  spark-worker-2:
    image: apache-spark-instance
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
        - ./apps:/opt/apps
        - ./data:/opt/data
    container_name: spark-worker-2